name: GHCup Setup
description: Download a pre-built version of GHCup and add it to the PATH
author: Andrea Bedini

branding:
  icon: download

inputs:
  version:
    description: GHCup version to install
    default: latest
  release-channels:
    description: Set the release-channels (deprecated, use 'config' instead)
  stack-hook:
    description: Install the GHCup stack hook (GHCs are installed through ghcup)
    default: false
  ghc:
    description: GHC version to install
  cabal:
    description: cabal-install version to install
  stack:
    description: Stack version to install
  hls:
    description: HLS version to install
  config:
    description: GHCup config (partial or full)
    default: '{"meta-cache": 0 }'

outputs:
  path:
    description: Path to the installed GHCup binary
  version:
    description: Version of the installed GHCup
  basedir:
    description: Base directory of GHCup
  bindir:
    description: Binary directory of GHCup
  cachedir:
    description: Cache directory of GHCup
  logsdir:
    description: Log directory of GHCup
  confdir:
    description: Config directory of GHCup

runs:
  using: node20
  main: ghcup/dist/index.js
